language: en

pipeline:
#  - name: "ConveRTTokenizer"
#    model_url: /Users/daksh/.cache/tfhub/1a04c4bb0262921a412ea61367f41fa4402f8841
##    model_url: https://github.com/PolyAI-LDN/polyai-models/releases/download/v1.0/model.tar.gz
#  - name: "ConveRTFeaturizer"
  - name: "HFTransformersNLP"
    model_name: "bert"
    model_weights: "rasa/LaBSE"
  - name: "LanguageModelTokenizer"
  - name: "LanguageModelFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: False
    epochs: 50
  - name: ResponseSelector
    epochs: 50

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
