language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 10
    constrain_similarities: true
    random_seed: 101
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 10
    constrain_similarities: true
    random_seet: 101

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
